defmodule SixTest do
  use ExUnit.Case
  alias AdventOfCode.Six

  test "part_one" do
    assert Six.part_one(
             TestUtils.Input.str_to_matrix("""
             ....#.....
             .........#
             ..........
             ..#.......
             .......#..
             ..........
             .#..^.....
             ........#.
             #.........
             ......#...
             """)
           ) == 41
  end

  test "find_guard_position" do
    assert Six.find_guard_position(
             TestUtils.Input.str_to_matrix("""
             ....#.....
             .........#
             ..........
             ..#.......
             .......#..
             ..........
             .#..^.....
             ........#.
             #.........
             ......#...
             """)
           ) == {6, 4}
  end

  test "make_move" do
    field =
      TestUtils.Input.str_to_matrix("""
      ....#.....
      .........#
      ..........
      ..#.......
      .......#..
      ..........
      .#..^.....
      ........#.
      #.........
      ......#...
      """)

    expected_field =
      TestUtils.Input.str_to_matrix("""
      ....0.....
      ....XXXXX0
      ....X...X.
      ..0.X...X.
      ..XXXXX0X.
      ..X.X.X.X.
      .1XXXXXXX.
      .XXXXXXX1.
      0XXXXXXX..
      ......0X..
      """)

    assert Six.make_move(field, 6, 4) == {false, expected_field}
  end

  test "part_two" do
    assert Six.part_two(
             TestUtils.Input.str_to_matrix("""
             ....#.....
             .........#
             ..........
             ..#.......
             .......#..
             ..........
             .#..^.....
             ........#.
             #.........
             ......#...
             """)
           ) == 6
  end
end
